image: python:3.7

stages:
  - production
  
production:
  type: deploy
  stage: production
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - pip install -r requirements.txt
  - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - main
