apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-app
  labels:
    app: recipe-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: recipe-app
  template:
    metadata:
      labels:
        app: recipe-app
    spec:
      containers:
      - name: recipe-app
        image: shreeda/recipeapi:latest 
        ports:
        - containerPort: 8000
          name: gunicorn
